services:
  db:
    image: mysql:8.0
    container_name: pizza_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RTX2080ti
      MYSQL_DATABASE: pizza_pizza
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: pizza
    volumes: 
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    ports:
      - '3306:3306'

volumes:
  mysql_data: